version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - image-data:/home/synthetix/images
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:4001,https://images.ashank.tech
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4001
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=secure_password_here
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - image-data:/home/synthetix/images
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  image-data:
    driver: local

networks:
  app-network:
    driver: bridge