version: '3.8'

services:
  app:
    build: .
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/image-uploader
      - NEXTAUTH_URL=http://localhost:4001
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - SITE_URL=http://localhost:4001
    volumes:
      - uploads:/app/uploads
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: unless-stopped

  # Optional: MongoDB admin interface
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:
  uploads:

networks:
  app-network:
    driver: bridge